export const jobsData = [
  {
    id: "1",
    title: "Software Developer",
    company: "XYZ Corp",
    location: "New York",
    description: "We are looking for a software developer to join our team.",
  },
  {
    id: "2",
    title: "Frontend Developer",
    company: "ABC Corp",
    location: "Los Angeles",
    description: "We are looking for a frontend developer to join our team.",
  },
  {
    id: "3",
    title: "Backend Developer",
    company: "123 Corp",
    location: "Chicago",
    description: "We are looking for a backend developer to join our team.",
  },
  {
    id: "4",
    title: "Fullstack Developer",
    company: "456 Corp",
    location: "San Francisco",
    description: "We are looking for a fullstack developer to join our team.",
  },
  {
    id: "5",
    title: "DevOps Engineer",
    company: "789 Corp",
    location: "Seattle",
    description: "We are looking for a DevOps engineer to join our team.",
  },
];

export const dummyUsers = [
  { username: "sam", password: "password", role: "admin" },
  { username: "magesh", password: "password", role: "user" },
];

export const skills = [
  { value: "React", label: "React" },
  { value: "Node.js", label: "Node.js" },
  { value: "JavaScript", label: "JavaScript" },
  { value: "TypeScript", label: "TypeScript" },
  { value: "CSS", label: "CSS" },
  { value: "HTML", label: "HTML" },
  { value: "Python", label: "Python" },
  { value: "Java", label: "Java" },
  { value: "C++", label: "C++" },
  { value: "C#", label: "C#" },
  { value: "PHP", label: "PHP" },
  { value: "Ruby", label: "Ruby" },
  { value: "Swift", label: "Swift" },
  { value: "Go", label: "Go" },
  { value: "SQL", label: "SQL" },
  { value: "NoSQL", label: "NoSQL" },
  { value: "Docker", label: "Docker" },
  { value: "Kubernetes", label: "Kubernetes" },
  { value: "AWS", label: "AWS" },
  { value: "Azure", label: "Azure" },
  { value: "GCP", label: "GCP" },
  { value: "Git", label: "Git" },
  { value: "GitHub", label: "GitHub" },
  { value: "Bitbucket", label: "Bitbucket" },
  { value: "Jira", label: "Jira" },
  { value: "Confluence", label: "Confluence" },
  { value: "Slack", label: "Slack" },
  { value: "Trello", label: "Trello" },
  { value: "Jenkins", label: "Jenkins" },
  { value: "NPM", label: "NPM" },
  { value: "Yarn", label: "Yarn" },
];

export const locations = [
  { value: "Remote", label: "Remote" },
  { value: "New York", label: "New York" },
  { value: "Los Angeles", label: "Los Angeles" },
  { value: "Chicago", label: "Chicago" },
  { value: "San Francisco", label: "San Francisco" },
  { value: "Seattle", label: "Seattle" },
  { value: "Houston", label: "Houston" },
  { value: "Phoenix", label: "Phoenix" },
  { value: "Philadelphia", label: "Philadelphia" },
  { value: "San Diego", label: "San Diego" },
  { value: "Dallas", label: "Dallas" },
  { value: "San Jose", label: "San Jose" },
  { value: "Austin", label: "Austin" },
  { value: "Jacksonville", label: "Jacksonville" },
  { value: "San Antonio", label: "San Antonio" },
  { value: "Columbus", label: "Columbus" },
  { value: "Charlotte", label: "Charlotte" },
  { value: "Indianapolis", label: "Indianapolis" },
  { value: "Detroit", label: "Detroit" },
  { value: "El Paso", label: "El Paso" },
  { value: "Memphis", label: "Memphis" },
  { value: "Boston", label: "Boston" },
];
